/* -*- tab-width: 4 -*-
 *
 * Electric(tm) VLSI Design System
 *
 * File: TruthTablePanel.java
 * Truth table analysis from simulation waveform data.
 *
 * Copyright (c) 2026, Static Free Software. All rights reserved.
 *
 * Electric(tm) is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 */
package com.sun.electric.tool.user.waveform;

import com.sun.electric.tool.simulation.Signal;
import com.sun.electric.tool.simulation.DigitalSample;
import com.sun.electric.tool.simulation.ScalarSample;
import com.sun.electric.tool.simulation.Sample;

import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.util.*;
import java.util.List;

/**
 * Panel that displays a truth table derived from simulation waveform data.
 * Analyzes input and output signals to build a combinational truth table.
 *
 * For analog signals, uses a voltage threshold (VDD/2) to determine HIGH/LOW.
 * For digital signals, reads the logic state directly.
 *
 * The truth table is generated by sampling signals at each unique time step
 * where any input changes value.
 */
public class TruthTablePanel extends JPanel
{
    private final WaveformWindow waveWindow;
    private JTable truthTable;
    private DefaultTableModel tableModel;
    private JLabel statusLabel;
    private JComboBox<String> thresholdSelector;
    private double threshold = 0.9; // default: VDD/2 for 1.8V

    // Selected signals
    private List<Signal<?>> inputSignals = new ArrayList<>();
    private List<Signal<?>> outputSignals = new ArrayList<>();

    public TruthTablePanel(WaveformWindow ww)
    {
        super(new BorderLayout(0, 4));
        this.waveWindow = ww;
        setPreferredSize(new Dimension(350, 400));
        setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));

        // Header
        JPanel headerPanel = new JPanel(new BorderLayout(4, 2));
        JLabel titleLabel = new JLabel("Truth Table");
        titleLabel.setFont(titleLabel.getFont().deriveFont(Font.BOLD, 13f));
        headerPanel.add(titleLabel, BorderLayout.WEST);

        // Threshold selector
        JPanel threshPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 2, 0));
        threshPanel.add(new JLabel("Vth:"));
        thresholdSelector = new JComboBox<>(new String[]{"0.9V (1.8V)", "1.65V (3.3V)", "2.5V (5V)", "Custom..."});
        thresholdSelector.setPreferredSize(new Dimension(120, 24));
        thresholdSelector.addActionListener(e -> {
            int idx = thresholdSelector.getSelectedIndex();
            switch (idx)
            {
                case 0: threshold = 0.9; break;
                case 1: threshold = 1.65; break;
                case 2: threshold = 2.5; break;
                case 3:
                    String val = JOptionPane.showInputDialog(this, "Enter threshold voltage:", String.valueOf(threshold));
                    if (val != null) try { threshold = Double.parseDouble(val); } catch (Exception ex) {}
                    break;
            }
            rebuild();
        });
        threshPanel.add(thresholdSelector);
        headerPanel.add(threshPanel, BorderLayout.EAST);
        add(headerPanel, BorderLayout.NORTH);

        // Table
        tableModel = new DefaultTableModel();
        truthTable = new JTable(tableModel);
        truthTable.setFont(new Font("Monospaced", Font.PLAIN, 12));
        truthTable.setRowHeight(22);
        truthTable.getTableHeader().setReorderingAllowed(false);

        // Custom renderer for 0/1/X coloring
        truthTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
        {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column)
            {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setHorizontalAlignment(SwingConstants.CENTER);
                if (!isSelected && value != null)
                {
                    String v = value.toString();
                    if (v.equals("1")) setForeground(new Color(0x2E7D32)); // green
                    else if (v.equals("0")) setForeground(new Color(0x1565C0)); // blue
                    else if (v.equals("X") || v.equals("Z")) setForeground(Color.RED);
                    else setForeground(Color.BLACK);

                    // Highlight output columns
                    if (column >= inputSignals.size())
                        setBackground(isSelected ? table.getSelectionBackground() : new Color(0xFFF8E1));
                    else
                        setBackground(isSelected ? table.getSelectionBackground() : Color.WHITE);
                }
                return c;
            }
        });

        JScrollPane scrollPane = new JScrollPane(truthTable);
        add(scrollPane, BorderLayout.CENTER);

        // Status bar
        statusLabel = new JLabel("Select signals in waveform panels, then click Analyze");
        statusLabel.setFont(statusLabel.getFont().deriveFont(11f));
        statusLabel.setBorder(BorderFactory.createEmptyBorder(2, 4, 2, 4));

        JPanel bottomPanel = new JPanel(new BorderLayout());
        JButton analyzeBtn = new JButton("Analyze");
        analyzeBtn.addActionListener(e -> analyzeFromPanels());
        bottomPanel.add(statusLabel, BorderLayout.CENTER);
        bottomPanel.add(analyzeBtn, BorderLayout.EAST);
        add(bottomPanel, BorderLayout.SOUTH);
    }

    /**
     * Auto-detect input/output signals from all waveform panels.
     * Convention: signals with names containing "in", "a", "b", "c", "clk" → input
     * Signals with names containing "out", "y", "sum", "carry", "q" → output
     * Otherwise: first half = input, second half = output
     */
    public void analyzeFromPanels()
    {
        inputSignals.clear();
        outputSignals.clear();

        // Collect all displayed signals
        List<Signal<?>> allSignals = new ArrayList<>();
        for (Iterator<Panel> it = waveWindow.getPanels(); it.hasNext(); )
        {
            Panel panel = it.next();
            for (WaveSignal ws : panel.getSignals())
            {
                allSignals.add(ws.getSignal());
            }
        }

        if (allSignals.isEmpty())
        {
            statusLabel.setText("No signals displayed. Add signals to waveform first.");
            return;
        }

        // Classify: highlighted signals are outputs, rest are inputs
        // If no highlighting, use name-based heuristic
        Set<Signal<?>> highlightedSet = new HashSet<>();
        for (Iterator<Panel> it = waveWindow.getPanels(); it.hasNext(); )
        {
            Panel panel = it.next();
            for (WaveSignal ws : panel.getSignals())
                if (ws.isHighlighted()) highlightedSet.add(ws.getSignal());
        }

        if (!highlightedSet.isEmpty())
        {
            // Highlighted = output, rest = input
            for (Signal<?> s : allSignals)
            {
                if (highlightedSet.contains(s)) outputSignals.add(s);
                else inputSignals.add(s);
            }
        }
        else
        {
            // Name-based classification
            for (Signal<?> s : allSignals)
            {
                String name = s.getSignalName().toLowerCase();
                if (name.contains("out") || name.contains("sum") || name.contains("carry") ||
                    name.contains("cout") || name.equals("y") || name.equals("q") || name.equals("s"))
                    outputSignals.add(s);
                else
                    inputSignals.add(s);
            }
            // If all classified as input, move last half to output
            if (outputSignals.isEmpty() && inputSignals.size() >= 2)
            {
                int half = inputSignals.size() / 2;
                outputSignals.addAll(inputSignals.subList(half, inputSignals.size()));
                inputSignals = new ArrayList<>(inputSignals.subList(0, half));
            }
        }

        rebuild();
    }

    /**
     * Set signals explicitly (called from external code).
     */
    public void setSignals(List<Signal<?>> inputs, List<Signal<?>> outputs)
    {
        this.inputSignals = new ArrayList<>(inputs);
        this.outputSignals = new ArrayList<>(outputs);
        rebuild();
    }

    /**
     * Rebuild the truth table from current input/output signals.
     */
    public void rebuild()
    {
        if (inputSignals.isEmpty() || outputSignals.isEmpty())
        {
            tableModel.setRowCount(0);
            tableModel.setColumnCount(0);
            statusLabel.setText(inputSignals.size() + " inputs, " + outputSignals.size() + " outputs");
            return;
        }

        // Build column names
        String[] columns = new String[inputSignals.size() + outputSignals.size()];
        for (int i = 0; i < inputSignals.size(); i++)
            columns[i] = inputSignals.get(i).getSignalName();
        for (int i = 0; i < outputSignals.size(); i++)
            columns[inputSignals.size() + i] = outputSignals.get(i).getSignalName();

        tableModel.setColumnIdentifiers(columns);
        tableModel.setRowCount(0);

        // Collect all time points where inputs change
        List<Signal<?>> allSignals = new ArrayList<>(inputSignals);
        allSignals.addAll(outputSignals);

        TreeSet<Double> changeTimes = new TreeSet<>();
        for (Signal<?> sig : allSignals)
        {
            Signal.View<? extends Sample> view = sig.getExactView();
            if (view == null) continue;
            for (int i = 0; i < view.getNumEvents(); i++)
                changeTimes.add(view.getTime(i));
        }

        if (changeTimes.isEmpty())
        {
            statusLabel.setText("No simulation data found");
            return;
        }

        // Sample at each change time, deduplicate rows
        Set<String> seenRows = new LinkedHashSet<>();
        List<String[]> rows = new ArrayList<>();

        for (double time : changeTimes)
        {
            String[] row = new String[columns.length];
            StringBuilder rowKey = new StringBuilder();

            // Sample inputs
            for (int i = 0; i < inputSignals.size(); i++)
            {
                row[i] = sampleSignal(inputSignals.get(i), time);
                rowKey.append(row[i]);
            }

            // Skip if we've seen this input combination
            String inputKey = rowKey.toString();
            // Sample outputs for this input combination
            for (int i = 0; i < outputSignals.size(); i++)
            {
                row[inputSignals.size() + i] = sampleSignal(outputSignals.get(i), time);
                rowKey.append("|").append(row[inputSignals.size() + i]);
            }

            String fullKey = rowKey.toString();
            if (!seenRows.contains(inputKey))
            {
                seenRows.add(inputKey);
                rows.add(row);
            }
        }

        // Sort rows by input binary value
        rows.sort((a, b) -> {
            for (int i = 0; i < inputSignals.size(); i++)
            {
                int va = "1".equals(a[i]) ? 1 : 0;
                int vb = "1".equals(b[i]) ? 1 : 0;
                if (va != vb) return va - vb;
            }
            return 0;
        });

        // Add to table
        for (String[] row : rows)
            tableModel.addRow(row);

        statusLabel.setText(inputSignals.size() + " inputs, " + outputSignals.size() +
            " outputs, " + rows.size() + " unique rows (Vth=" + threshold + "V)");
    }

    /**
     * Sample a signal at a given time, returning "0", "1", "X", or "Z".
     */
    @SuppressWarnings("unchecked")
    private String sampleSignal(Signal<?> sig, double time)
    {
        if (sig.isDigital())
        {
            Signal.View<DigitalSample> view = ((Signal<DigitalSample>) sig).getExactView();
            if (view == null || view.getNumEvents() == 0) return "X";

            // Find the sample at or just before the given time
            DigitalSample sample = null;
            for (int i = view.getNumEvents() - 1; i >= 0; i--)
            {
                if (view.getTime(i) <= time + 1e-15)
                {
                    sample = view.getSample(i);
                    break;
                }
            }
            if (sample == null) sample = view.getSample(0);

            if (sample.isLogic1()) return "1";
            if (sample.isLogic0()) return "0";
            if (sample.isLogicX()) return "X";
            return "Z";
        }
        else
        {
            // Analog: use threshold
            Signal.View<ScalarSample> view;
            try { view = ((Signal<ScalarSample>) sig).getExactView(); }
            catch (Exception e) { return "X"; }
            if (view == null || view.getNumEvents() == 0) return "X";

            double value = 0;
            for (int i = view.getNumEvents() - 1; i >= 0; i--)
            {
                if (view.getTime(i) <= time + 1e-15)
                {
                    value = view.getSample(i).getValue();
                    break;
                }
            }

            if (Double.isNaN(value) || Double.isInfinite(value)) return "X";
            return value >= threshold ? "1" : "0";
        }
    }
}
